### ISSUE TITLE
Support React 15

### ISSUE THREAD

**Issue by steve-taylor** [vakhtang/react-search-bar#10]

**Comment by castrolem** [comment]
This, there's a PR open that solves this problem also. 👍

**Comment by grinono** [comment]
any update on this? Module is not working in react 15.2.1

**Comment by pierluigi** [comment]
+1

**Comment by vakhtang** [comment]
2.0 is out, but I don't plan on actively maintaining this project. It's now available for educational purposes. Please use [react-autosuggest](https://github.com/moroshko/react-autosuggest) instead.
