### ISSUE TITLE
NPM module out of date?

### ISSUE THREAD

**Issue by andrewhill10X** [vakhtang/react-search-bar#11]
Thanks for publishing this, it looks great!

I installed this with NPM and it seems to be missing many of the features listed on github (including different properties, etc.).

Would it be possible to:
1. Let me know what the best way to install from the github repository is (I have tried several things and not had much success, so if you have any tips that would be great).

or 
1. Update the NPM package to reflect the changes

or 
1. Recommend an alternative if you are not interested in either 1 or 2?

Thanks for the help!
Andrew

**Comment by vakhtang** [comment]
Hi Andrew. I no longer maintain this repo and will be deprecating this module soon, so your best bet would be to use [react-autosuggest](https://github.com/moroshko/react-autosuggest). It's got a lot more features and is WA-ARIA compliant.
