### ISSUE TITLE
No tabbing or arrow navigation

### ISSUE THREAD

**Issue by BradyEdgar94** [vakhtang/react-search-bar#15]
I love this component's simplicity and look forward to using it in future projects, unfortunately I am going to need to add tabbing or arrow key navigation for the suggestions or else my app will not be compliant with the disability aiding standards I need to meet. So adding an arrow key navigation seems like a must for this component. I would love to help out if need be, but just bringing the issue to light on here right now.

**Comment by vakhtang** [comment]
Thanks, but I don't plan on adding additional features at this point. Please use [react-autosuggest](https://github.com/moroshko/react-autosuggest) instead (if you haven't already), which should meet your requirements.
