### ISSUE TITLE
Submit/Search on Enter pressed

### ISSUE THREAD

**Issue by nicholaslie90** [vakhtang/react-search-bar#17]
Are there any options to perform search when the user presses Enter (from a desktop computer) or Submit/Search/Go from a mobile device keyboard?

**Comment by vakhtang** [comment]
`onSearch` is what you're looking for, but at this point I don't plan on actively maintaining this project. It's now available for educational purposes. Please use [react-autosuggest](https://github.com/moroshko/react-autosuggest) instead.
