### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by bitmapdata** [vakhtang/react-search-bar#20]
occur error when props suggestions is not empty.

![screen shot 2017-11-27 at 11 18 50 am](https://user-images.githubusercontent.com/3241312/33247924-0b03aa84-d365-11e7-951e-1e2b018bf3fe.png)

**Comment by vakhtang** [comment]
I’m on vacation with limited Internet access but I’ll get to it when I return.

**Comment by vakhtang** [comment]
@bitmapdata I'm unable to reproduce this. Could you provide a bit more detail or point to a fork?

**Comment by ghulamhussain** [comment]
how to use this component with typescript. is the the type definition available?

**Comment by vakhtang** [comment]
@ghulamhussain Type definitions aren’t available currently. Please open a separate issue.

**Comment by npasparuhov** [comment]
Same problem here with react 16:

    import React, { Component } from 'react';
    import SearchBar from 'react-search-bar';
    import './probe.scss';
    export class Probe extends Component {

    constructor(props) {
        super(props);

        this.state = {
        suggestions: []
        };
    }

    handleClear = () => {
        this.setState({
        suggestions: []
        });
    };

    handleChange = (input) => {
        let words = ['abasement',
        'abhor',
        'abrasive',
        'abrogate',
        'absolution',
        'abstain',
        'abstemious',
        'abstruse']
        this.setState({
        suggestions: words.filter(word => word.startsWith(input))
        });
    };

    handleSelection = (value) => {
        if (value) {
        console.info("Selected '${value}'");
        }
    };

    handleSearch = (value) => {
        if (value) {
        console.info("Searching '${value}'");
        }
    };

    suggestionRenderer = (suggestion, searchTerm) => {
        return (
        <span>
            <span>{searchTerm}</span>
            <strong>{suggestion.substr(searchTerm.length)}</strong>
        </span>
        );
    };

    render() {
        return (
        <div className='probe'>
            <SearchBar
            autoFocus
            renderClearButton
            renderSearchButton
            placeholder="select an SAT word"
            onChange={this.handleChange}
            onClear={this.handleClear}
            onSelection={this.handleSelection}
            onSearch={this.handleSearch}
            suggestions={this.state.suggestions}
            suggestionRenderer={this.suggestionRenderer}
            />
        </div>
        );
    }
    }


The code from above is ok on first render, but when you type something and it need to render the suggestions it gives this error:

```
invariant.js:42 Uncaught Error: Expected ref to be a function or a string.
    at invariant (invariant.js:42)
    at coerceRef (react-dom.development.js:6735)
    at createChild (react-dom.development.js:6977)
    at reconcileChildrenArray (react-dom.development.js:7282)
    at reconcileChildFibers (react-dom.development.js:7651)
    at reconcileChildrenAtExpirationTime (react-dom.development.js:7756)
    at reconcileChildren (react-dom.development.js:7747)
    at updateHostComponent (react-dom.development.js:7998)
    at beginWork (react-dom.development.js:8229)
    at performUnitOfWork (react-dom.development.js:10224)

react-dom.development.js:9747 The above error occurred in the <ul> component:
    in ul
    in Suggestions
    in div
    in SearchBar (created by Probe)
    in div (created by Probe)
    in Probe (created by App)
    in div (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

**Comment by vakhtang** [comment]
Not maintained anymore. Please fork and modify as needed.
