### ISSUE TITLE
Getting results via fetch()

### ISSUE THREAD

**Issue by haydenth** [vakhtang/react-search-bar#7]
Hello - I'm having a hard time calling the resolve() function within the context of a fetch call (i'm getting the data by remotely querying our search index). resolve does nothing and the dropdown does not populate. Any suggestions? Here's my onChange function

```
  _runSearch(input, resolve) {
    var search_url = 'https://blpt.co/company-search';
    var payload = {query: input};

    fetch(search_url, {method: 'POST', body: JSON.stringify(payload)})
      .then((result) => {return result.json()})
      .then((res) => {
        var list = [];
        resolve(['asdf', 'basdf']);
      })
      .done()
  },
```

for instance, this does not populate a dropdown for me or even do anything (despite results being returned). Am I doing anything obviously incorrect? Apologies, I am not a very good javascript coder.

**Comment by vakhtang** [comment]
Your code looks fine to me. What's the value of `res`? It needs to be an array of strings. Also, are you sure that you make it to the second `then`?
